# Generated by Django 3.2.5 on 2021-09-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_alter_historymodel_queries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historymodel',
            old_name='status',
            new_name='typeQuery',
        ),
        migrations.AlterField(
            model_name='historymodel',
            name='url',
            field=models.CharField(default='', max_length=300, verbose_name='URL'),
        ),
    ]
