# Generated by Django 3.2.5 on 2021-09-27 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_childmodel_statusnet'),
        ('history', '0006_alter_historymodel_queries'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueriesGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usermodel')),
            ],
            options={
                'verbose_name': 'Группа запросов',
                'verbose_name_plural': 'Группы запросов',
            },
        ),
        migrations.RemoveField(
            model_name='queriesmodel',
            name='user',
        ),
        migrations.AlterField(
            model_name='queriesmodel',
            name='typeQuery',
            field=models.CharField(blank=True, choices=[('URL', 'Сайт'), ('WORD', 'Фраза'), ('QUERY', 'Запрос')], default='', max_length=100, verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='QueryGroupToChildModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.childmodel', verbose_name='Пользователь')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.queriesgroupmodel', verbose_name='Группа запросов')),
            ],
            options={
                'verbose_name': 'Связь',
                'verbose_name_plural': 'Связи',
            },
        ),
        migrations.AddField(
            model_name='queriesmodel',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='history.queriesgroupmodel'),
        ),
    ]
