# Generated by Django 3.2.5 on 2021-09-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0009_rename_typequery_queriesmodel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='historymodel',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
    ]
