# Generated by Django 3.2.5 on 2021-09-29 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0010_historymodel_last_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historymodel',
            old_name='last_updated',
            new_name='date',
        ),
    ]
